
# 服务端口
server :
  port : 8080
  tomcat :
    uri-encoding : UTF-8
    max-threads : 500
  error:
    path: /error
  servlet:
      session:
        timeout: 30m
      context-path: /thymeleaf

# 日志
logging :
    level :
      org :
        springframework : INFO

# spring
spring :
  # thymeleaf
  thymeleaf :
    # 是否开启缓存，default=true
    cache : true
    # 检查模板是否存在,default=true
    check-template : true
    # 检查模板位置是否存在，default=true
    check-template-location : true
    # 模板文件编码
    encoding : UTF-8
    # 模板文件位置,default：classpath:/templates/
    prefix : classpath:/templates/
    # Content-Type 配置
    servlet.content-type : text/html
    # 模板文件后缀,default=.html
    suffix : .html


